// Coral from a binary tree.
//
// A soft coral is a recursive fork: a trunk that splits in two, each half
// splitting again, thinner and shorter each time, until the last forks end
// in fingers dotted with polyps. This bakes that recursion into a pure SVG
// <symbol> so the page (and, later, the screen saver) needs no script at run
// time. Deterministic: the same seed always draws the same coral.
//
// Motion: every branch is its own joint. The placing transform sits on an
// outer <g>; the animated <g class="sway-dN"> inside it pivots on the branch
// base, whose position we compute here as a transform-origin in fill-box
// pixels. Deeper levels bend more and later, so the tree bends like a tree.
//
//   node tools/coral-gen.mjs            # splice into atoms.html
//   node tools/coral-gen.mjs --print 7  # print one symbol to stdout

import { readFileSync, writeFileSync } from "node:fs";

const SEEDS = [
  { id: "coral-a", seed: 7 },
  { id: "coral-b", seed: 21 },
  { id: "coral-c", seed: 42 },
];

const DEPTH = 5;          // forks; 2^DEPTH fingers
const TRUNK = 42;         // trunk length
const RATIO = 0.72;       // each level is this much shorter
const SPREAD = 26;        // degrees off the parent, before jitter
const JITTER = 11;        // degrees of per-fork randomness
const WIDTH = 13;         // trunk width at the base
const TAPER = 0.66;       // width per level

function rng(seed) {
  // mulberry32 — small, deterministic, good enough for a coral
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const f = (n) => Math.round(n * 10) / 10;
const rad = (d) => (d * Math.PI) / 180;

// Build one branch. Returns its markup and the points of its whole subtree
// in this branch's own frame (base at 0,0, growing up the -y axis), which is
// what the joint's transform-origin needs.
function branch(rand, depth, len, w) {
  const wTip = w * TAPER;
  const pts = [
    [-w / 2, 0], [w / 2, 0], [-wTip / 2, -len], [wTip / 2, -len],
  ];
  const tone = depth <= 1 ? "var(--coral-dark)" : "var(--coral)";
  let inner = `<path d="M${f(-w / 2)},0 L${f(-wTip / 2)},${f(-len)} L${f(wTip / 2)},${f(-len)} L${f(w / 2)},0 Z" fill="${tone}"/>`;
  if (depth >= 2) {
    // a lit rib up the branch, the side the lamp sees
    inner += `<path d="M${f(-wTip / 4)},${f(-len * 0.15)} L${f(-wTip / 4)},${f(-len * 0.9)}" stroke="var(--polyp)" stroke-width="1" opacity=".35" fill="none"/>`;
  }

  if (depth === DEPTH - 1) {
    // the finger at the end of the last fork, and its polyps
    const ry = 9 + rand() * 4;
    const rx = 4.5 + rand() * 1.5;
    inner += `<ellipse cx="0" cy="${f(-len - ry + 2)}" rx="${f(rx)}" ry="${f(ry)}" fill="var(--coral)" stroke="var(--coral-dark)" stroke-width="1"/>`;
    const dots = [[-rx * 0.45, -len - ry * 0.6], [rx * 0.4, -len - ry * 1.1], [0, -len - ry * 1.7], [-rx * 0.3, -len - ry * 1.4]];
    for (const [x, y] of dots) {
      inner += `<circle cx="${f(x)}" cy="${f(y)}" r="${f(1.3 + rand() * 0.6)}" fill="var(--polyp)"/>`;
      pts.push([x, y]);
    }
    pts.push([-rx, -len], [rx, -len - 2 * ry]);
  } else {
    // fork: two children, each on its own joint
    const bias = (rand() - 0.5) * JITTER;
    for (const side of [-1, 1]) {
      const a = side * (SPREAD + (rand() - 0.5) * JITTER) + bias;
      const childLen = len * RATIO * (0.9 + rand() * 0.2);
      const child = branch(rand, depth + 1, childLen, wTip);
      // child frame → this frame: rotate(a) then translate(0,-len)
      const c = Math.cos(rad(a)), s = Math.sin(rad(a));
      for (const [x, y] of child.pts) pts.push([x * c - y * s, x * s + y * c - len]);
      inner += `<g transform="translate(0,${f(-len)}) rotate(${f(a)})">${child.svg}</g>`;
    }
  }

  const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
  const minX = Math.min(...xs) - 1, minY = Math.min(...ys) - 1;
  // fill-box origin: the base (0,0) measured from the subtree's top-left corner
  const svg = `<g class="sway-d${depth}" style="transform-origin:${f(-minX)}px ${f(-minY)}px">${inner}</g>`;
  return { svg, pts };
}

function coral({ id, seed }) {
  const rand = rng(seed);
  const root = branch(rand, 0, TRUNK, WIDTH);
  return (
    `      <!-- ${id} — generated by tools/coral-gen.mjs, seed ${seed}: a binary tree ${DEPTH} forks deep, ${2 ** DEPTH} fingers. Origin at the base. -->\n` +
    `      <symbol id="${id}" overflow="visible">${root.svg}</symbol>\n`
  );
}

const args = process.argv.slice(2);
if (args[0] === "--print") {
  process.stdout.write(coral({ id: "coral", seed: Number(args[1] ?? 7) }));
} else {
  const page = new URL("../atoms.html", import.meta.url);
  let html = readFileSync(page, "utf8");
  const BEGIN = "      <!-- CORAL:BEGIN (generated) -->\n";
  const END = "      <!-- CORAL:END -->\n";
  const block = BEGIN + SEEDS.map(coral).join("") + END;
  const i = html.indexOf(BEGIN), j = html.indexOf(END);
  if (i >= 0 && j >= 0) {
    html = html.slice(0, i) + block + html.slice(j + END.length);
  } else {
    // first run: replace the hand-drawn coral symbol
    const start = html.indexOf("      <!-- SOFT CORAL");
    const end = html.indexOf("</symbol>", start) + "</symbol>\n".length;
    if (start < 0) throw new Error("no coral symbol to replace");
    html = html.slice(0, start) + block + html.slice(end);
  }
  writeFileSync(page, html);
  console.log(`spliced ${SEEDS.length} corals into atoms.html`);
}
